<a href="https://colab.research.google.com/github/iamonk/Ml_with_python_cookbook/blob/main/Chapter_1_(Vectors%2C_Matrices_and_Array).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Matrix
matrix_object=np.mat([[1,2],[3,4],[5,6]])

In [ ]:
matrix_object

matrix([[1, 2],
        [3, 4],
        [5, 6]])

## We didn't use Matrix datastructure (1.As array is the de facto standard structure of Numpy and majority of function return arrays not matrix object)

In [ ]:
from scipy import sparse

In [ ]:
#Creating a Sparse Matrix
mt=np.array([[0,0],[0,1],[3,0]])
mt_sparse=sparse.csr_matrix(mt)

In [ ]:
print(mt_sparse)

  (1, 1)	1
  (2, 0)	3


In [ ]:
mt_large=np.array([[0,0,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[3,0,0,0,0,0,0,0,0,0]])
mt_large_sparse=sparse.csr_matrix(mt_large)
print(mt_large_sparse)

  (1, 1)	1
  (2, 0)	3


## In practical machine learning experience there are many elements which are zero,which leads to computational problem. To get rid of extra zero and computational power we sparse the matrix or array. 
# Example: Netflix movie's and how many user watch it, Its obvious most user didn' watch all the movie(0) 

In [ ]:
#Selecting
mt2=np.array([[1,2,3],[4,5,6],[7,8,9]])
# all rows and 2 and 3 column
mt2[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
#first 2 rows and all column
mt2[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#all rows and 2nd column
mt2[:,1:2]

array([[2],
       [5],
       [8]])

In [ ]:
#Describing a matrix
mt2.shape,mt2.size,mt2.ndim

((3, 3), 9, 2)

## Vectorization And Broadcasting 
(Vectorization is just like a for loop and doesn't increase performance)
Broadcasting(Only Numpy allows us)

In [ ]:
add_100=lambda i:i+100

In [ ]:
vectorized_add_100 = np.vectorize(add_100)
vectorized_add_100(mt2)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [ ]:
#Broadcasting (Very Fast)
mt2+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [ ]:
#Max and Min
np.max(mt2),np.min(mt2)

(9, 1)

In [ ]:
#column wise
np.max(mt2,axis=0)

array([7, 8, 9])

In [ ]:
#row wise
np.min(mt2,axis=1)

array([1, 4, 7])

In [ ]:
#Mean, Variance and Std
np.mean(mt2),np.var(mt2),np.std(mt2)

(5.0, 6.666666666666667, 2.581988897471611)

In [ ]:
#Reshaping(Size must remain same)
mt2.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
mt2.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
mt3=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [ ]:
mt3.shape

(4, 3)

In [ ]:
mt3.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
#Imp(-1 means as many as needed)
mt3.reshape(2,-1),mt3.reshape(3,-1)

(array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [ ]:
#Transposing
mt3.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [ ]:
#Flatterning a matrix(Reshape a matrix into 1d array simply saying .reshape(1,-1)
mt3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
mt3.flatten(order='F')

array([ 1,  4,  7, 10,  2,  5,  8, 11,  3,  6,  9, 12])

## Flatten in Column Major but default is Row major(Which is faster as iterating in continuos memory is faster than jumping back and forth which we seen in column Major(above example))

In [ ]:
#Rank of matrix
np.linalg.matrix_rank(mt2)

2

In [ ]:
#Determinant (Must be square)
np.linalg.det(mt2)

0.0

In [ ]:
#diagonal
mt3.diagonal()

array([1, 5, 9])

In [ ]:
mt3.diagonal(offset=1),mt3.diagonal(offset=-1) #(+ve for above the daigonal and -ve for below the diagonal)

(array([2, 6]), array([ 4,  8, 12]))

In [ ]:
mt3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#Trace (Sum of diagonal)
mt3.trace()

15

In [ ]:
sum(mt3.diagonal())

15

In [ ]:
#EigenValues And EigenVector
#must be square
EigenValues,EigenVector = np.linalg.eig((mt2))
EigenValues,EigenVector

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [76]:
eigval,eigvc=np.linalg.eig(mt2)

# Eigenvectors are widely used in machine learning libraries. Intuitively, given a linear transformation represented by a matrix, A, eigenvectors are vectors that, when that transformation is applied, change only in scale (not direction). More formally: Av = λv where A is a square matrix, λ contains the eigenvalues and v contains the eigenvec‐ tors. In NumPy’s linear algebra toolset, eig lets us calculate the eigenvalues, and eigenvectors of any square matrix.

In [79]:
#Dot Product (Matrix Multiplication)
mt4=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(mt2,mt4)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [80]:
#Add and subtract you can simply use (+ or -) or (np.add,np.subtract)
mt2+mt4

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [82]:
np.subtract(mt2,mt4)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
## Element Wise Multiplication(a*b) and Dot wise Multiplication (a@b)
mt2*mt4

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [84]:
mt2 @ mt4

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [95]:
#Inversing A matrix
mt5=np.array([[1,4],[2,5]])

In [98]:
inv=np.linalg.inv(mt5)

In [99]:
mt5 @ inv

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [100]:
#Random Number
np.random.seed(seed=0)
mt6=np.random.random((3,4))

In [101]:
mt6

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [102]:
np.random.randint(1,10,size=(4,4))

array([[9, 2, 6, 9],
       [5, 4, 1, 4],
       [6, 1, 3, 4],
       [9, 2, 4, 4]])

In [108]:
np.random.rand(5,3)

array([[0.75068614, 0.60783067, 0.32504723],
       [0.03842543, 0.63427406, 0.95894927],
       [0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 ],
       [0.6235101 , 0.33800761, 0.67475232]])

In [ ]:
#Finished